spring.application.name=groupeCinq

# Configuration Resend
resend.api.key=re_Z9L8Wk3N_PnxSc7Mo3avEKon2yoNLjSba
resend.from.email=onboarding@resend.dev

# Configuration Notifications
notification.email=alexandre.levenez@ecoles-epsi.net

# Configuration Base de données pour les factures
spring.datasource.url=jdbc:postgresql://ep-tiny-waterfall-abk4tc7o-pooler.eu-west-2.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_8kCczmZOT0HM
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration HikariCP (pool de connexions)
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=300000

# Configuration JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
